### ISSUE TITLE
Why was Lottie removed?

### ISSUE THREAD

**Issue by jim-at-jibba** [calebnance/expo-multi-screen-starter#9]
Hey bud,

Just wondered why you removed the Lottie animation from loading? Interested as I was gonna use it but won't if you know of any reasons not too.

Thanks for this package.

**Comment by calebnance** [comment]
hey hey,

my implementation i felt was a little off (some times on load i would get errors on response) and it is still in the DangerZone within expo, so i decided to remove it. wanted to keep this as boilerplate as possible i guess too

**Comment by jim-at-jibba** [comment]
@calebnance ok cool, that is good to know. 

I will take a look at other avenues.

I hope you dont mind, I created a typescript version of this boilerplate. All credit points to you :)

https://github.com/jim-at-jibba/expo-multiscreen-typescript-starter

**Comment by calebnance** [comment]
no i don't mind at all but thanks for giving credit! i'm glad it helped, do you like the directory structure? i feel it's pretty solid but would love any feedback to always make things better
